version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 7000:7000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - yashvardhan
networks:
  yashvardhan:
